name: Update ReadMe
run-name: Update ReadMe
on:
  schedule:
    - cron:  '00 8 * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ env.GH_TOKEN }}

      - name: Run Script
        run: bash ./scripts/gh-call.sh

      - name: Commit to master
        continue-on-error: true
        run: |
          git config user.name hmcts-platform-operations
          git config user.email github-platform-operations@hmcts.net
          git add .
          git commit -m "auto update modules"
          git push